application: valentinetagtoo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /valentine_static
  static_dir: dist/static

- url: /valentine_semantic
  static_dir: node_modules/semantic-ui/dist

- url: /valentine_libs
  static_dir: node_modules/Tagtoo_tools/libs

- url: /valentine_game.html
  static_files: dist/game.html
  upload: dist/game.html

- url: /valentine_card.html
  static_files: dist/card.html
  upload: dist/card.html

- url: /valentine_get.html
  static_files: dist/get.html
  upload: dist/get.html

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
